name: ritual_app
description: "Memento - memory app"
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  go_router: ^15.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  intro_slider: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.5
  bottom_sheet: ^4.0.0
  intl: ^0.19.0
  http: ^1.2.0
  cloud_firestore: ^5.6.2
  url_launcher: ^6.2.5
  firebase_storage: ^12.4.1
  get_it: ^8.0.3
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.1
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.3
  # device_info_plus: ^11.2.1
  video_player: ^2.8.6
  mime: ^2.0.0
  mobile_scanner: ^6.0.10
  video_compress: ^3.1.2
  google_sign_in: ^6.2.1
  tab_container: ^3.5.3
  video_thumbnail: ^0.5.3
  uuid: ^4.5.1
  pretty_qr_code: ^3.4.0
  # welltested: ^0.0.1

  # firebase_messaging: ^14.6.0
  # flutter_local_notifications: ^14.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.8
  freezed: ^2.5.7
  hive_generator: ^2.0.0

### TODO Launch
flutter_launcher_icons:
  image_path: "assets/app_icon/memento_icon.png"
  # image_path_android: "assets/images/icon-710x599-android.png"
  # image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/app_icon/LifeSync-01.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  # background_color_ios: "#9BCD8F"

# # to run this use dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/splash/memento_splash.png
  color: "#FFFFFF"

  android_12:
    color: "#FFFFFF"
    image: assets/splash/memento_splash.png

flutter:
  uses-material-design:
    true

    # Enables generation from arb files
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/intro/
    - assets/socials/
    - assets/menu_icons/
    - assets/fonts/Dosis/static/Dosis-Regular.ttf
    - assets/fonts/Poppins/Poppins-Regular.ttf
    - assets/fonts/Sansita/Sansita-Regular.ttf
    - assets/fonts/Signika/static/Signika-Regular.ttf
    - assets/fonts/Signika/static/Signika-Medium.ttf
    - assets/fonts/MedievalSharp/MedievalSharp-Regular.ttf
