// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIIaZAbkKZ72c3e0o_akgo-SWQh6uWQk8',
    appId: '1:961628958004:web:60b77d6f9529b473fac961',
    messagingSenderId: '961628958004',
    projectId: 'ritualapp-5c7c7',
    authDomain: 'ritualapp-5c7c7.firebaseapp.com',
    storageBucket: 'ritualapp-5c7c7.appspot.com',
    measurementId: 'G-ZKD1QWZGJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpqiHw4HC283g0G4Dd3WLj-6SBSlKUgOo',
    appId: '1:961628958004:android:866bedd06ead6a9dfac961',
    messagingSenderId: '961628958004',
    projectId: 'ritualapp-5c7c7',
    storageBucket: 'ritualapp-5c7c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOI42kceNTn6NiuOwDKXncPqke21u8qJ0',
    appId: '1:961628958004:ios:65a8766b00d4a7dafac961',
    messagingSenderId: '961628958004',
    projectId: 'ritualapp-5c7c7',
    storageBucket: 'ritualapp-5c7c7.appspot.com',
    iosBundleId: 'com.personal.ritualApp',
  );
}
